[phases.setup]
nixPkgs = { php = "8.2", composer = "latest" }

[phases.install]
cmds = ["cd inventarioBackend && composer install --optimize-autoloader --no-dev"]

[start]
cmd = "cd inventarioBackend && php artisan serve --host=0.0.0.0 --port=$PORT"

